import React from "react";
import { Helmet, HelmetProvider } from "helmet";

import MouseUnderlay from './MouseUnderlay.jsx'
import Header from './Header.jsx'

const Ultra = ({ helmetContext }) => {
  return (
    <>
      <HelmetProvider context={helmetContext}>
        <Helmet>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1"
          />
          <meta charset="UTF-8" />

          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Amita:wght@400;700&family=Kadwa:wght@400;700&family=Kalam:wght@300;400;700&family=Khula:wght@300;400;600;700;800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Tillana:wght@400;500;600;700;800&display=swap" rel="stylesheet" />

          <link rel="stylesheet" href="/style.css" />

          <title>मनु सिंह गिल</title>
        </Helmet>

        <Header />
        <main>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque a dui sed sapien semper porttitor ac ut enim. Maecenas vulputate pulvinar hendrerit. Nulla dapibus diam enim, quis sodales turpis lacinia eu. Mauris porta arcu non eros porta commodo. Nam ante mi, mollis a cursus nec, eleifend ac massa. Phasellus posuere maximus justo, vitae interdum nisi eleifend sed. Duis ac risus ex. Donec sit amet maximus dolor. Maecenas pretium, tortor vehicula imperdiet porta, sapien ligula mollis augue, in vehicula nibh orci id nulla. Mauris nunc sem, interdum id lorem gravida, eleifend faucibus sapien.</p>
<p>Sed scelerisque nunc quis eros tempus, id fringilla metus iaculis. Nulla ut egestas sem, vel condimentum dui. Morbi tempor sapien a mattis gravida. Cras sodales nibh eget diam euismod, hendrerit efficitur elit rhoncus. Duis ac augue a sem pellentesque iaculis. Nullam eu nisi at eros aliquam tempor nec nec magna. In velit lorem, dapibus quis neque rutrum, dictum pretium nunc. Aliquam feugiat ut turpis eleifend vulputate. Nunc iaculis ante dapibus diam tincidunt luctus ac a tellus. Nullam non massa at sem aliquam blandit a sit amet mauris. Duis elementum elit id orci pretium finibus. Vestibulum ut pulvinar neque, id iaculis elit. Praesent eget dapibus purus. Phasellus finibus malesuada vehicula. Morbi lobortis vel urna at auctor.</p>
<p>Curabitur commodo, urna eget interdum interdum, nunc est ultricies lacus, nec consequat nulla nunc id ligula. Ut sagittis neque eget tristique ullamcorper. Vivamus id sapien diam. Vestibulum leo mi, euismod vitae feugiat ultricies, auctor vel leo. Aenean pellentesque eleifend libero id bibendum. Cras ut augue lacinia, blandit mauris vitae, semper erat. Quisque in felis in nunc eleifend maximus. Fusce id ultrices dui. Integer varius, augue sed tempor vulputate, enim nisi hendrerit mi, et varius odio libero vel lorem. Nam scelerisque mattis convallis. Suspendisse vel nisi vitae arcu bibendum maximus. Sed condimentum mauris neque, scelerisque faucibus nisl efficitur quis.</p>
<p>Maecenas sagittis orci eros, at sollicitudin turpis porttitor efficitur. Etiam vulputate lorem ac elementum egestas. Sed auctor elementum massa, id luctus nisl luctus vel. Quisque est odio, ultrices ut vulputate nec, pharetra a turpis. Duis elementum molestie feugiat. Phasellus ultrices consectetur eros sit amet pretium. Aenean hendrerit dui id leo rutrum placerat. Aliquam erat volutpat.</p>
<p>Sed ullamcorper tellus a lacus iaculis egestas. Aliquam consequat ac mi a ullamcorper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce venenatis vel eros ut scelerisque. Duis ante mauris, convallis in arcu a, tincidunt dignissim enim. Duis eget tincidunt ex. Praesent lacinia, lacus non efficitur posuere, purus leo bibendum erat, a posuere nisl lorem sed massa. Sed vel tortor placerat, venenatis nisl a, volutpat eros. Fusce vitae lacus vulputate, ultricies ex eu, malesuada nulla. Morbi congue maximus mollis. Nam eros sem, dignissim quis lacinia vitae, blandit eget ex. Maecenas fermentum, purus a interdum elementum, magna ex scelerisque turpis, sit amet tincidunt nulla ex vel turpis. Maecenas vulputate, tortor et dapibus porta, neque lectus ullamcorper nisl, non tincidunt ante purus in nunc. Vestibulum tempor erat bibendum facilisis faucibus.</p>
<p>Duis ut elit ac eros dictum ultricies sit amet vel leo. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce fermentum, sem non porta molestie, nibh est elementum arcu, a porttitor elit odio quis dui. Aliquam blandit neque metus, sit amet rhoncus nulla euismod non. Proin blandit eros mauris, vel commodo erat fermentum in. Aenean a tristique ex. Aenean dictum vestibulum pellentesque. Quisque lacinia, orci id euismod mattis, nisi sem dictum ipsum, at ornare magna massa quis metus. Ut ac facilisis lorem, vel ullamcorper nisl. Vivamus quis mollis diam, eget vehicula enim.</p>
<p>Sed pharetra cursus justo vitae ornare. Quisque pharetra dui odio, sit amet ullamcorper diam mollis in. Phasellus quis libero consequat, volutpat tellus ac, rhoncus turpis. Aliquam consequat est dui, nec condimentum turpis ultricies non. Maecenas iaculis sollicitudin elit, non fringilla nibh mollis feugiat. Nulla rutrum purus purus, varius mattis nibh pretium in. In eu turpis pharetra, gravida leo congue, malesuada mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sed dui at magna dictum scelerisque vel sit amet orci. Pellentesque varius mi nec fringilla tincidunt. Proin dictum nibh at magna dictum varius. Ut sollicitudin et libero id ultricies. Integer id diam non purus viverra scelerisque quis vel libero. Donec interdum tempus est id interdum. Nullam eget justo sit amet lectus venenatis lacinia. Integer at enim ut orci ullamcorper accumsan sit amet sed justo.</p>
<p>Ut vehicula sapien ac nibh porta, et consectetur dolor pharetra. Sed fermentum dolor vel lorem lacinia tincidunt. Maecenas non vehicula lectus. Vestibulum sed neque tortor. Pellentesque porta erat sed rhoncus aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam a massa ut ligula sollicitudin ultrices. Suspendisse ut dolor porta, vehicula ligula eget, convallis massa. Fusce sollicitudin venenatis velit, vitae aliquet mauris pretium ut. Curabitur nulla massa, rutrum non augue quis, condimentum vehicula eros.</p>
<p>Morbi porttitor porta nulla id sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris blandit bibendum lacus id consequat. Mauris hendrerit ac augue gravida feugiat. Sed et est arcu. Vivamus id sollicitudin ex. In arcu mauris, venenatis et orci quis, consectetur iaculis lacus. Donec mollis lorem ligula, id efficitur nibh auctor et. Nam eget velit nisi. Cras porta congue auctor. Proin vitae consectetur dolor. Donec in erat et dui pellentesque suscipit. Donec sed ligula eget risus ullamcorper consectetur eget quis mauris. Vivamus id interdum nulla.</p>
<p>Donec malesuada metus vitae nisi condimentum, id accumsan ex egestas. Cras magna diam, porta nec aliquet vitae, volutpat non mi. Curabitur nec blandit odio, elementum euismod dui. Duis iaculis, ante eget accumsan congue, elit eros feugiat felis, id ultricies velit leo nec elit. Morbi faucibus tempus risus id bibendum. Nulla eleifend lacinia velit. Nunc aliquam sed arcu vel vehicula. Aliquam dapibus nisi nec imperdiet tempor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
<p>Cras quis leo faucibus, placerat ligula sit amet, pretium enim. Pellentesque vitae commodo ipsum. Donec quam risus, facilisis quis euismod vitae, vestibulum et dui. Cras placerat est et erat bibendum finibus. Vestibulum accumsan eros leo, id eleifend libero laoreet eget. Morbi mollis nisl at est facilisis iaculis. Aenean varius, justo a maximus pulvinar, est lectus fermentum lacus, a pulvinar massa massa ac velit. Etiam rutrum ornare ullamcorper. Etiam at est ut nisi sollicitudin condimentum. Cras scelerisque pretium nunc. Praesent iaculis gravida magna a mattis. Integer sit amet mauris ut odio sagittis commodo ac sed nibh. In luctus dignissim sodales. Cras in suscipit felis. Fusce sagittis pharetra nisi at dictum. Nulla facilisi.</p>
<p>Sed at odio quam. Ut sit amet mauris et orci dictum pharetra. Cras cursus ipsum sit amet justo lacinia cursus. Sed feugiat sed neque ut tempor. Suspendisse potenti. Pellentesque interdum justo est. Curabitur fermentum gravida convallis. Sed facilisis, sapien vel pharetra blandit, mauris purus tincidunt eros, non volutpat nisl diam et dolor. Proin vitae varius ex. Nullam placerat gravida luctus. Vivamus tortor urna, congue a lacus nec, consequat dictum justo.</p>
<p>Aenean ut finibus lacus. Phasellus ultricies sollicitudin neque. Donec a orci ligula. Proin accumsan id mi id tincidunt. Morbi id turpis non ipsum scelerisque sollicitudin. Fusce vitae placerat leo, finibus molestie ex. Nam vitae elit ut nunc gravida maximus at vel quam. Pellentesque nisl purus, pellentesque sagittis nulla et, porta malesuada justo. Maecenas sit amet pretium sem, viverra rhoncus purus. Integer rhoncus dolor et elit venenatis ornare. Nunc dapibus varius ante ut dapibus. Fusce vitae lacus sed nisi fermentum pulvinar pellentesque et ipsum. Nulla leo dui, ultrices vitae leo ac, lobortis iaculis risus. Sed dolor lacus, congue vitae eros vel, hendrerit lobortis ligula. Duis luctus, quam eu ullamcorper venenatis, ante erat tincidunt orci, et pellentesque ex est nec tellus.</p>
<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam eros dui, egestas ac feugiat at, luctus vitae dolor. Donec cursus tempor ipsum ut viverra. Curabitur euismod nisl at nisi elementum, eu efficitur diam lacinia. Integer sed orci at felis tincidunt rhoncus. Proin suscipit a lectus in bibendum. Donec vehicula mauris vitae eros tristique dignissim. Aliquam tincidunt fringilla sapien, eget rhoncus lorem porta in. Maecenas fringilla malesuada congue. In at dictum mi. Aenean egestas lacinia risus dictum maximus. Quisque tempor magna odio, vitae congue tellus feugiat et.</p>
<p>Ut vel sem ac eros luctus congue. In ac enim nunc. Nunc et erat lobortis, lacinia est ac, dignissim purus. Sed sem nisi, tincidunt quis libero nec, luctus pellentesque purus. In ut commodo dui, id ornare nibh. Donec lobortis, eros et dignissim ultricies, nibh leo bibendum ante, id vulputate ex risus a orci. Pellentesque varius metus sit amet sagittis dignissim. Praesent sed lectus fermentum, pulvinar nulla a, rutrum mi. Mauris tincidunt purus a odio facilisis pharetra. Etiam ullamcorper tristique est id malesuada. Donec dictum justo in ipsum commodo, vitae viverra lectus volutpat. Maecenas eu sem vestibulum, blandit ex at, ornare turpis. Nullam semper lobortis consequat. Maecenas finibus tristique est, eu fringilla libero ultricies non. Cras porta mattis ante, id lobortis lorem vulputate sed.</p>
        </main>

      </HelmetProvider>
      <MouseUnderlay />
    </>
  );
};

export default Ultra;
